### ISSUE TITLE
Loading in Squeak fails with error “Name not found: Grease-Core”

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Parasol#10]
See [Travis CI job 248.5](https://travis-ci.org/SeasideSt/Parasol/jobs/240416631#L742) for Squeak-4.6: loading failed on “Error: Name not found: Grease-Core”. The same error seems to have occurred in all builds since [build 244](https://travis-ci.org/SeasideSt/Parasol/jobs/239322999#L920). In [job 243.4](https://travis-ci.org/SeasideSt/Parasol/jobs/239096805#L3163), the tests were still run.

**Comment by jbrichau** [comment]
My suggestion: drop Squeak 4.6... nobody from the Squeak community is helping to maintain all compatibility. We try to keep compatible with latest version only.

**Comment by Rinzwind** [comment]
I assume that means it's not just a small mistake that would be easy to fix? I guess in that case we can restrict Squeak support to version 5 from now on.

**Comment by jbrichau** [comment]
The problem is in keeping all possible configurations and versions working. It might not be that much work, but there always is work associated and the people working on this have limited time. So, we dropped older versions of Squeak.
