### ISSUE TITLE
Links to the corresponding Java API documentation are broken

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Parasol#19]
Some of the comments in methods that refer to the documentation of the corresponding Java API method use the old website, for example:

https://github.com/SeasideSt/Parasol/blob/03b6b67ae9f382aaaca124c9e06c5a33531431b1/repository/Parasol-Core.package/BPRemoteWebDriver.class/instance/findElementByName..st#L5

Fixing this seems to be just be a matter of replacing `http://selenium.googlecode.com/svn/trunk/` by `https://seleniumhq.github.io/selenium/`, and replacing `(` and `)` by `-`. For the above example, the new URL is:

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html#findElementByName-java.lang.String-

**Comment by jbrichau** [comment]
This was fixed in https://github.com/SeasideSt/Parasol/pull/39
