### ISSUE TITLE
Loading in Squeak v5.2 signals an error stating “This package must not be used”

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Parasol#24]
Loading Parasol in Squeak v5.2 fails, with an error stating:

```
Error: This package must not be used. It was split in 2015 into: WebClient-Seaside-Adatpor and WebClient-Seaside-Tools-Development
```

See: https://travis-ci.org/SeasideSt/Parasol/jobs/466712494#L757

**Comment by jbrichau** [comment]
Fixed in Seaside 3.3.0 (https://github.com/SeasideSt/Seaside/issues/1069)
