### ISSUE TITLE
Would be cool to be able to initialize the state of a component at the beginning of a test case.

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Parasol#3]
For example I want to test a paginated table. 

In a first test I would like to test the table with few data to get only one page.

In the second test I would like to test the table with multiple pages.

**Comment by Rinzwind** [comment]
I don't really understand what the issue is here. Could you please provide a more concrete example of how the Parasol test framework makes it impossible or hard to implement your scenario?

**Comment by jecisc** [comment]
When I create a test class for a paginated table I need to give the name of the class of the component and Parasol will create an instance.

During a test Parasol will open a web page with this component. 

Currently there is no hook between the creation of the component and the opening of the web page to change the state of the component. 

In the case of my paginated table I would like to add some rows in the test #testPaginatedTableWithOnePage and I would like to add a lot of rows in the test #testPaginatedTableWithManyPages.
