### ISSUE TITLE
Testing fails on Pharo 5

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Parasol#33]
Testing fails on Pharo 5, see: https://travis-ci.org/SeasideSt/Parasol/jobs/550959588#L993

The whole job fails, without a test report.

**Comment by Rinzwind** [comment]
The error (`MessageNotUnderstood: WAUrl>>asByteArray`) seems to happen in the context of running `BPMiscTestCase>>#testFileUpload`.

Workaround: use the version of `WAResponse>>#location:` from before the change done in https://github.com/SeasideSt/Seaside/commit/7fc5186e4648edaf0a3a9d38bb8e595a915e1680#diff-bc2773a86a65dd44cbc514c5b6c0b7f7. The test then works, as do all other tests, with the exception of `BPRemoteWebDriverTestCase>>#testCookies`. The latter seems to fail for the same reason as in Squeak (`MessageNotUnderstood: WACookie>>oldNetscapeString`), see issue #32.

**Comment by Rinzwind** [comment]
For now, I marked the test as one to be skipped on Pharo 5 (https://github.com/SeasideSt/Parasol/commit/5930a0738baca3390162f013f25e6abd4ba8b8f7).

**Comment by Rinzwind** [comment]
Instead of skipping the test, I added a Smalltalk-CI post-loading script to patch `WAResponse>>#location:` and `WACookie>>#oldNetscapeString` (https://github.com/SeasideSt/Parasol/commit/f697d80e02140648ac0797d6284dd743a1248720), as well as `WACookie>>#rfc2965String` (https://github.com/SeasideSt/Parasol/commit/09b72f56519bc2bf99ac6886a4ed29b80fb6b554).

**Comment by jbrichau** [comment]
@Rinzwind That looks more like a bug in Seaside to me, because older Pharo versions have older Zinc loaded. I quickly added the issue so we can fix it there (SeasideSt/Seaside#1141)

**Comment by jbrichau** [comment]
We dropped Pharo 5 support anyway, so we can remove it here as well and close the issue.
