### ISSUE TITLE
New versions of chromedriver seem pegged to specific Chrome versions

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Parasol#34]
Newer versions of chromedriver seem to be pegged to specific Chrome versions. While v2.41 of chromedriver seems to allow using Chrome 75.0.3770.100; the newer v2.45 refuses to create a session, returning an error instead saying “Chrome version must be between 70 and 73”.

Implication: we may need to update chromedriver more often, or specify the version of Chrome to use in the “.travis.yml” file as well.

**Comment by Rinzwind** [comment]
The [notes for ChromeDriver](http://chromedriver.chromium.org/downloads) v2.45 state:

> ChromeDriver 2.45
>
> Supports Chrome v70-72
> * Fixed New Session is not spec compliant
> * Fixed ChromeDriver shouldn't launch Chrome if Chrome and ChromeDriver versions are incompatible

**Comment by jbrichau** [comment]
Github actions builds (added in #48) now download a package that does the automatic matching for us. The Travis-CI builds don't.
