### ISSUE TITLE
Example code fail with latest version of Chrome

### ISSUE THREAD

**Issue by shamsulazhar** [SeasideSt/Parasol#36]
**OS:** MacOS
**Pharo version:** Pharo5.0 Latest update: #50772
**Chrome version:** Version 76.0.3809.87 (Official Build) (64-bit)
**Chrome Driver version:** ChromeDriver 76.0.3809.68

**Problem:**
When running the Wikipedia example code, it fails at the following line :-

`(driver findElementByID: 'searchInput') click.
`

**Error Message:** "KeyNotFound: key 'ELEMENT' not found in Dictionary

**Comment by SabineMa** [comment]
Having same problem with this config:

OS: MacOS
Pharo version: Pharo7.0.3
Chrome version: Version 76.0.3809.100 (Offizieller Build) (64-Bit)
Chrome Driver version: 76.0.3809.126

**Comment by Rinzwind** [comment]
Sorry about that. It seems that we forgot to update the example in commit ddfb600. This has now been fixed in commit b05c10c. I'm closing this issue, but let us know if it's still not working for you.

**Comment by SabineMa** [comment]
Hi Kris, 
I checked and it works fine now with the example changed.
Thanks a lot.
Sabine
