### ISSUE TITLE
endless loop when loading parasol before mdl (or voyage)

### ISSUE THREAD

**Issue by SabineMa** [SeasideSt/Parasol#47]
I load in my baseline Parasol, voyage, mdl (and other stuff).

I have noticed that I have to load mdl and voyage **before** parasol to avoid getting an endless loop 

could be related with (but I do NOT use GemStone):
https://github.com/SeasideSt/Parasol/issues/43

I can fix the problem by changing order but I want to report it here.
With the following baseline the endless loop can be reproduced:

```
baseline: spec
	<baseline>
	spec
		for: #common
		do: [ spec blessing: #baseline.
			spec
				baseline: 'Parasol'
				with: [ spec
						loads: #('core');
						repository: 'github://SeasideSt/Parasol/repository' ].
			spec
				baseline: 'MaterialDesignLite'
				with: [ spec repository: 'github://DuneSt/MaterialDesignLite:v2.2.4/src' ] ]
```

![Bildschirmfoto 2020-10-28 um 13 10 49](https://user-images.githubusercontent.com/13763544/97434424-48250b80-191f-11eb-8098-ae1ffafc37c0.png)

**Comment by jbrichau** [comment]
This should be fixed in #48
