### ISSUE TITLE
Fix setup for Pharo 11.0?

### ISSUE THREAD

**Issue by Dima-369** [SeasideSt/Parasol#57]
Hey, I wanted to try this out but when I evaluate this, I get a `KeyError` because of `ZnZincServerAdaptor`?

```smalltalk
Metacello new
    baseline: 'Parasol';
    repository: 'github://SeasideSt/Parasol:master/repository';
    load: 'default'.
(Smalltalk at: #ZnZincServerAdaptor) startOn: 8080.
```

![image](https://user-images.githubusercontent.com/15002298/178472411-4e3c19e9-cb79-41cd-856c-5bf7faf57c67.png)

**Comment by jbrichau** [comment]
Hi @Dima-369 
Seaside etc have not configuration for loading into the Pharo 11 development branch.

Until this has been done, if you want to try this out, you can use Pharo 10 right now. Does that work for you?

**Comment by Dima-369** [comment]
> Until this has been done, if you want to try this out, you can use Pharo 10 right now. Does that work for you?

I loaded a fresh Pharo 10.0 image and executed the block from the issue description and it shows the same error?

**Comment by jbrichau** [comment]
Ok, I notice now that the snippet in the README still assumes we are loading Seaside in the default metacello group. This has been changed to avoid a circular dependency.
You can either load Seaside first, or load the 'tests' group:

```
Metacello new
    baseline: 'Parasol';
    repository: 'github://SeasideSt/Parasol:master/repository';
    load: 'tests'.
(Smalltalk at: #ZnZincServerAdaptor) startOn: 8080.
```

**Comment by Dima-369** [comment]
With `load: 'tests'`, the installation even works in Pharo 11.0, so closing this.
